# Önce mysql master servisini başlat
# - monitor_user ve monitor_password ile monitor kullanıcısı oluşturuyoruz.
# - proxysql için gerekli kullanıcıları oluşturuyoruz
# Multi-master Group Replication için 3 master node kuruluyor

services:
  setup:
    image: mysql:5.7
    container_name: mysql_setup
    working_dir: /
    entrypoint: /run.sh
    volumes:
      - ./run.sh:/run.sh
    depends_on:
      master3:
        condition: service_healthy
    networks:
      - mysql_network

  master1:
    image: mysql:5.7
    container_name: master1
    hostname: master1
    restart: unless-stopped
    command: --defaults-file=/etc/mysql/my.cnf --server-id=1
    volumes:
      - ./master1.cnf:/etc/mysql/my.cnf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - master1_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33061:3306"
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  master2:
    image: mysql:5.7
    container_name: master2
    hostname: master2
    restart: unless-stopped
    command: --defaults-file=/etc/mysql/my.cnf --server-id=2
    volumes:
      - ./master2.cnf:/etc/mysql/my.cnf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - master2_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33062:3306"
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      master1:
        condition: service_healthy

  master3:
    image: mysql:5.7
    container_name: master3
    hostname: master3
    restart: unless-stopped
    command: --defaults-file=/etc/mysql/my.cnf --server-id=3
    volumes:
      - ./master3.cnf:/etc/mysql/my.cnf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - master3_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33063:3306"
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      master2:
        condition: service_healthy

networks:
  mysql_network:
    driver: bridge

volumes:
  master1_data:
  master2_data:
  master3_data:

  # # MySQL Slave 1
  # mysql-slave-1:
  #   image: mysql:5.7
  #   command: >
  #     --server-id=2
  #     --relay-log=mysql-relay-bin
  #     --log-bin=mysql-bin
  #     --binlog-format=ROW
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     TZ: Europe/Istanbul
  #   volumes:
  #     - slave_data_1:/var/lib/mysql
  #     - ./slave-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - mysql-network
  #   depends_on:
  #     mysql-master:
  #       condition: service_healthy

  # # MySQL Slave 2
  # mysql-slave-2:
  #   image: mysql:5.7
  #   command: >
  #     --server-id=3
  #     --relay-log=mysql-relay-bin
  #     --log-bin=mysql-bin
  #     --binlog-format=ROW
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     TZ: Europe/Istanbul
  #   volumes:
  #     - slave_data_2:/var/lib/mysql
  #     - ./slave-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "3309:3306"
  #   networks:
  #     - mysql-network
  #   depends_on:
  #     mysql-master:
  #       condition: service_healthy

  # ProxySQL
#   proxysql:
#     image: proxysql/proxysql
#     container_name: proxysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       TZ: Europe/Istanbul
#     volumes:
#       - ./proxysql.cnf:/etc/proxysql.cnf
#       - /etc/localtime:/etc/localtime:ro
#     ports:
#       - "6032:6032" # Admin arayüzü için
#       - "6033:6033" # MySQL bağlantı portu
#     networks:
#       - mysql-network
#     depends_on:
#       - mysql-master
#       - mysql-slave-1
#       - mysql-slave-2

#   # phpMyAdmin
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: proxysql
#       PMA_USER: app_user
#       PMA_PASSWORD: app_pass123
#       PMA_PORT: 6033
#       TZ: Europe/Istanbul
#     ports:
#       - "8080:80"
#     networks:
#       - mysql-network
#     depends_on:
#       - proxysql

# networks:
#   mysql-network:

# volumes:
#   master_data:
#   slave_data_1:
#   slave_data_2: